kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: {{name}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
spec:
  image: {{image}}
  ingresses:
    {{#each ingresses}}
       - "{{this}}"
    {{/each}}
  liveness:
    path: /isAlive
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 30
  replicas:
    min: 1
    max: 2
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  cpuThresholdPercentage: 80
  #vault:
  #  enabled: true
  #  paths:
  #    {{#each vault-paths}}
  #       - kvPath: "{{this.kvPath}}"
  #         mountPath: "{{this.mountPath}}"
  #    {{/each}}
  env:
    {{#each envs}}
       - name: "{{this.name}}"
         value: "{{this.value}}"
    {{/each}}